version: "3.8"

services:
  sonarr:
    image: ghcr.io/hotio/sonarr:v4
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./config/sonarr-config:/config
      - ${DATA_FOLDER}:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./config/radarr-config:/config
      - ${DATA_FOLDER}:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./config/bazarr-config:/config
      - ${DATA_FOLDER}:/data
    ports:
      - "6767:6767"
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8111:8000/tcp
      - 8070:8070
    volumes:
      - ./config/gluetun-config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= #
      - WIREGUARD_ADDRESSES= #
      - SERVER_CITIES= #
      - TZ=Europe/Zurich
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Zurich
      - WEBUI_PORT=8070
    volumes:
      - ./config/qbittorrent-config:/config
      - ${DATA_FOLDER}/torrents:/data/torrents
      #- ./nightwalker:/opt/nightwalker # Nightwalker theme
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=13006
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ./config/plex-config:/config
      - ${DATA_FOLDER}/media:/media
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    environment:
      - TZ=Europe/Zurich
    volumes:
      - ./config/tautulli-config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./config/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Zurich
    ports:
      - "8191:8191"
    restart: unless-stopped
