services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.37.0.5076
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.15.2941
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/sonarr-config:/config
      - ${DATA_FOLDER}:/data
      - ${ADDITIONAL_SHARE}:/data2
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:release-5.26.2.10099
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/radarr-config:/config
      - ${DATA_FOLDER}:/data
      - ${ADDITIONAL_SHARE}:/data2
    ports:
      - 7878:7878
    restart: unless-stopped

  profilarr:
    image: santiagosayshey/profilarr:v1.1.2
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/profilarr-config:/config
    environment:
      - TZ=Europe/Zurich
    restart: unless-stopped

  lidarr:
    image: ghcr.io/hotio/lidarr:release-2.12.4.4658
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/lidarr-config:/config
      - ${DATA_FOLDER}:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.5.2
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/bazarr-config:/config
      - ${DATA_FOLDER}:/data
      - ${ADDITIONAL_SHARE}:/data2
    ports:
      - 6767:6767
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.25
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Zurich
    ports:
      - 8191:8191
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:1.42.1
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}  # optional
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/plex-config:/config
      - ${DATA_FOLDER}/media:/media
      - ${ADDITIONAL_SHARE}:/media-synology
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  tautulli:
    image: ghcr.io/hotio/tautulli:release-2.15.3
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/tautulli-config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  overseerr:
    image: ghcr.io/hotio/overseerr:release-1.34.0
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/overseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/jellyseerr-config:/app/config
    ports:
      - 5056:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release-5.1.2
    ports:
      - 8070:8070
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0-bak
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=192.168.8.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=  #
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Zurich
      - WEBUI_PORTS=8070/tcp,8070/udp
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/qbittorrent-config:/config
      - ${DATA_FOLDER}/torrents:/data/torrents
    restart: unless-stopped
