version: "3.9"

services:
  app:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data

networks:
  proxy:
    external: true