name: komodo-periphery

services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.3
    container_name: komodo-periphery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      - ${PERIPHERY_ADDITIONAL_DIRECTORY}:${PERIPHERY_ADDITIONAL_DIRECTORY}
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/keys:/config/keys
    environment:
      - PERIPHERY_ROOT_DIRECTORY=${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      - PERIPHERY_CORE_ADDRESS=${PERIPHERY_CORE_ADDRESS:?error}
      - PERIPHERY_CONNECT_AS=${PERIPHERY_CONNECT_AS:?error}
      - PERIPHERY_CORE_PUBLIC_KEYS=${PERIPHERY_CORE_PUBLIC_KEYS:-file:/config/keys/core.pub}
      - PERIPHERY_ONBOARDING_KEY=${PERIPHERY_ONBOARDING_KEY}
      - PERIPHERY_DISABLE_TERMINALS=false
      - PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
      - DOCKER_DATA_DIR=${DOCKER_DATA_DIR:-/opt/infra-data}
    network_mode: host
    restart: unless-stopped
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    init: true
