version: "3"

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads

networks:
  proxy:
    external: true