version: "3.1"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
    # with discord notifications
    # uses slack config for discord
    # replace webhook with your discord webhook, make sure to include the /slack
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL= # your discord webhook
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER= # name
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI= # emoji
      - TZ=Europe/Zurich
      - WATCHTOWER_HTTP_API_TOKEN= #your token
      - WATCHTOWER_HTTP_API_METRICS=true
    networks:
      - proxy
    ports:
      - "6666:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  proxy:
    external: true