services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
    # with discord notifications
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_NO_PULL: true
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "myserver" # change to whatever you wanna call your server in notifications
      WATCHTOWER_NOTIFICATION_URL: "" # your discord webhook: discord://webhook_token@webhook_id
      TZ: "Europe/Zurich"
      WATCHTOWER_HTTP_API_TOKEN: "" #your token
      WATCHTOWER_HTTP_API_METRICS: true
    ports:
      - "6666:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped