version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft_server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VIEW_DISTANCE: 18
      MEMORY: 6G
      DIFFICULTY: normal

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data