name: epic-games-free-games

services:
  free-games-claimer:
    image: ghcr.io/claabs/epicgames-freegames-node:3f2cf01a0ae36fffdfd91f7c0ae8c35677522c20
    container_name: epic-free-games
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/:/usr/app/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - "3887:3000"
    restart: unless-stopped
