name: dispatcharr

services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.22.0
    container_name: dispatcharr
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    ports:
      - "9191:9191"
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
