name: adguard-exporter

services:
  adguard-exporter:
    image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.1
    container_name: adguard-exporter
    environment:
      - ADGUARD_SERVERS=${ADGUARD_SERVERS:?error}
      - ADGUARD_USERNAMES=${ADGUARD_USERNAMES:?error}
      - ADGUARD_PASSWORDS=${ADGUARD_PASSWORDS:?error}
    ports:
      - "9618:9618"
    restart: unless-stopped
