name: adguard-exporter

services:
  adguard-exporter:
    image: ghcr.io/znandev/adguardexporter:v1.2.3
    container_name: adguard-exporter
    environment:
      - ADGUARD_HOST=${ADGUARD_HOST:?error}
      - ADGUARD_USER=${ADGUARD_USER:?error}
      - ADGUARD_PASS=${ADGUARD_PASS:?error}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "9617:9617"
    restart: unless-stopped
