services:

  miner:
    image: rdavidoff/twitch-channel-points-miner-v2:2.0.0
    container_name: twitch-points-miner
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    environment:
      - TERM=xterm-256color
    volumes:
      - ./analytics:/usr/src/app/analytics
      - ./cookies:/usr/src/app/cookies
      - ./logs:/usr/src/app/logs
      - ./run.py:/usr/src/app/run.py:ro
    restart: unless-stopped
