services:
  miner:
    image: rdavidoff/twitch-channel-points-miner-v2:latest
    container_name: twitch-points-miner
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TERM=xterm-256color
    volumes:
      - ./analytics:/usr/src/app/analytics
      - ./cookies:/usr/src/app/cookie s
      - ./logs:/usr/src/app/logs
      - ./run.py:/usr/src/app/run.py:ro
    ports:
      - "5000:5000"
