services:
  miner:
    image: rdavidoff/twitch-channel-points-miner-v2:2.0.0
    container_name: twitch-points-miner
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    environment:
      - TERM=xterm-256color
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/analytics:/usr/src/app/analytics
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/cookies:/usr/src/app/cookies
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/logs:/usr/src/app/logs
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/run.py:/usr/src/app/run.py:ro
    restart: unless-stopped
