name: czkawka

services:
  czkawka-web:
    image: ghcr.io/jackra1n/czkawka-web:1.0.0
    container_name: czkawka-web
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/data:/data
      - ${FILES_DIR}:/mnt/files
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5800:3000"
    cpus: 8.0
